// 화면에 보이는 문구를 전부 여기에 모아둡니다.
// 시안에서 문구 하나를 바꾸려고 60곳을 고친 적이 있어서(docs/00 참고),
// 실제 코드에서는 그런 일이 없도록 컴포넌트에 문구를 직접 쓰지 않습니다.
export const copy = {
  header: {
    brand: "봉사모아",
    login: "로그인",
    signup: "회원가입",
    logout: "로그아웃",
    defaultNickname: "회원",
  },
  auth: {
    signupTitle: "회원가입",
    loginTitle: "로그인",
    emailLabel: "이메일",
    emailPlaceholder: "you@example.com",
    passwordLabel: "비밀번호",
    passwordPlaceholder: "8자 이상",
    nameLabel: "이름",
    namePlaceholder: "현장에서 확인할 이름 (가입 후 수정 불가)",
    nicknameLabel: "닉네임",
    nicknamePlaceholder: "화면에 보여질 이름",
    sendCode: "인증번호 받기",
    sendingCode: "보내는 중...",
    codeLabel: "인증번호 6자리",
    codePlaceholder: "123456",
    verifyCode: "확인",
    verifyingCode: "확인 중...",
    codeSentNotice: (email: string) =>
      `${email} 로 인증번호를 보냈습니다. 메일함을 확인해주세요.`,
    emailVerifiedNotice: "이메일 인증이 완료됐습니다. 나머지 정보를 입력해주세요.",
    completeSignup: "가입 완료",
    completingSignup: "가입하는 중...",
    loginButton: "로그인",
    loggingIn: "로그인 중...",
    haveAccount: "이미 계정이 있으신가요?",
    noAccount: "계정이 없으신가요?",
    nicknameChecking: "확인 중...",
    nicknameAvailable: "사용할 수 있는 닉네임입니다.",
    nicknameTaken: "이미 사용 중인 닉네임입니다.",
  },
  errors: {
    invalidCode: "인증번호가 올바르지 않거나 만료됐습니다.",
    invalidLogin: "이메일 또는 비밀번호가 올바르지 않습니다.",
    passwordTooShort: "비밀번호는 8자 이상이어야 합니다.",
    nameRequired: "이름을 입력해주세요.",
    nicknameTooShort: "닉네임은 2자 이상이어야 합니다.",
    nicknameTaken: "이미 사용 중인 닉네임입니다.",
    emailTaken: "이미 가입된 이메일입니다. 로그인해주세요.",
    sessionMissing: "로그인 정보를 확인할 수 없습니다. 다시 시도해주세요.",
  },
} as const;
